### ISSUE TITLE
Google Sheets - Loading...

### ISSUE THREAD

**Issue by XAGSolutions** [ryan-d-williams/MMM-GoogleSheets#23] opened 2022-03-24 00:32 UTC
We are running into an issue with the module displaying data.

{
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_helper.js',
    '/Users/admin/MagicMirror/js/app.js',
    '/Users/admin/MagicMirror/js/electron.js',
    '/Users/admin/MagicMirror/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js',
    undefined
  ]

This part was resolved for the black screen with a previous issue report.

But after we got Magic Mirror to launch again we are only seeing a "Loading..." where the module is supposed to be.  We have rebooted, run all updates rebuilt using classic mode etc etc.

This is what terminal is spitting out:

[23.03.2022 17:29.20.187] [ERROR] Whoops! There was an uncaught exception...
[23.03.2022 17:29.20.189] [ERROR] SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_helper.js:47:27)
    at Request.self.callback (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)

Any help would be greatly appreciated.

**Comment by YeetGott** [comment] 2022-04-07 09:44
same problem

**Comment by redshiftgraphics** [comment] 2022-04-08 13:49
Debugging the code in Google Sheets Apps Script shows an error in the doGet() function. 

`TypeError: Cannot read property 'parameters' of undefined
doGet @  Code.gs:3`

**Comment by ryan-d-williams** [comment] 2022-04-09 17:31
@XAGSolutions @YeetGott @redshiftgraphics 

This is usually an issue with the MM configuration or the permissions for the google sheet you are trying to access.

If you can post your configuration you are using I can try to help you diagnose the problem.

**Comment by XAGSolutions** [comment] 2022-04-14 21:27
{
  module: "MMM-GoogleSheets",
  header: "ZENDESK",
  position: "top_right",
  config: {
    url: "https://script.google.com/macros/s/REDACTED_FOR_PRIVACY",
    sheet: "COUNTLIVE",
    range: "A1:A4",
    updateInterval: 1, // minutes
    requestDelay: 250 // ms
  }
},

**Comment by XAGSolutions** [comment] 2022-04-15 21:26
[15.04.2022 14:24.59.383] [ERROR] Whoops! There was an uncaught exception...
[15.04.2022 14:24.59.384] [ERROR] SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_helper.js:47:27)
    at Request.self.callback (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/admin/MagicMirror/modules/MMM-GoogleSheets/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)

**Comment by ryan-d-williams** [comment] 2022-04-17 02:56
@XAGSolutions this is usually caused when the parameters or permissions are incorrect.

I can't directly see the problem without the link. When you type the following address into your browser, what do you see?

https://script.google.com/macros/s/REDACTED_FOR_PRIVACY?sheet=COUNTLIVE&range=A1:A4

Note that you will need to change the url to be your actual url and not the redacted one. This is the actual request the module will make for the data, so if you don't see any data as a result then it is likely a problem with your parameters or permissions.

**Comment by XAGSolutions** [comment] 2022-04-21 01:15
@ryan-d-williams I added that REDACTED_FOR_PRIVACY for this post.  I have the actual correct link in my config file.

**Comment by XAGSolutions** [comment] 2022-04-21 01:18
<img width="708" alt="image" src="https://user-images.githubusercontent.com/46761745/164352452-9c0ea0a9-29c1-4633-9d78-45f59f4c0b77.png">
This is what I see when I go to the actual link.

**Comment by XAGSolutions** [comment] 2022-04-21 01:25
<img width="735" alt="image" src="https://user-images.githubusercontent.com/46761745/164353210-5fddec6e-f611-4ca2-a7ff-2bfed67c6603.png">
I also see this when I am logged in.

**Comment by XAGSolutions** [comment] 2022-04-28 17:01
@ryan-d-williams any advice on correcting this?  I have followed the walkthrough again on a new account and I am still getting the same lin 11 of code error.

**Comment by SARCux** [comment] 2022-05-16 16:01
I have the same problem
`TypeError: Cannot read property '0' of undefined (Zeile 11, Datei "Code")`

**Comment by shiring11** [comment] 2022-06-26 06:41
> I have the same problem
> `TypeError: Cannot read property '0' of undefined (Zeile 11, Datei "Code")`

same here...any solutions??

**Comment by ryan-d-williams** [comment] 2022-06-26 20:22
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/46761745/164352452-9c0ea0a9-29c1-4633-9d78-45f59f4c0b77.png">
> 
> This is what I see when I go to the actual link.

If this is what you see when you go to a link that is formatted like:
https://script.google.com/macros/s/REDACTED_FOR_PRIVACY?sheet=COUNTLIVE&range=A1:A4 
(where READACTED_FOR_PRIVACY) is replaced with your actual sheet id

Then it is definitely a permissions issue. It means your sheet has not been set for the "anyone" settings, which is why you're seeing that permissions screen. 

I went ahead and ran through the directions again to make sure they still work, and they do. It seems as though Google has updated the buttons to be in slightly different locations. I'll work to update the directions in the future.

@XAGSolutions the way to fix your problem is to double check your permissions as they are currently not set properly. They must be set so that anyone can access the script, even those not signed in (since your MM is not signed in). Feel free to post a screenshot of where you are setting the permissions and so we can give feedback if you are selecting the correct options.

**Comment by ryan-d-williams** [comment] 2022-06-26 20:25
@SARCux @shiring11 

Based on past issues and this thread, the most common cause of this problem is permissions not being set properly. If you do not have sensitive data, please post your configuration that you are using and I can make sure it is in fact a permissions problem and not something else. If you do have sensitive data, double check your permissions to make sure they are set appropriately. 

If you go to https://script.google.com/macros/s/[YOUR SHEET ID]?sheet=[YOUR SHEET NAME]&range=A1:A4
after replacing those values in brackets with your values, you should see actual data, as in the screenshot below. If you see a permissions screen that means your permissions were not set correctly.

![image](https://user-images.githubusercontent.com/65094007/175832552-3bc66abe-8579-4d02-a997-c329ff013995.png)

**Comment by shiring11** [comment] 2022-07-02 14:21
> @SARCux @shiring11
> 
> Based on past issues and this thread, the most common cause of this problem is permissions not being set properly. If you do not have sensitive data, please post your configuration that you are using and I can make sure it is in fact a permissions problem and not something else. If you do have sensitive data, double check your permissions to make sure they are set appropriately.
> 
> If you go to [https://script.google.com/macros/s/[YOUR](https://script.google.com/macros/s/%5BYOUR) SHEET ID]?sheet=[YOUR SHEET NAME]&range=A1:A4 after replacing those values in brackets with your values, you should see actual data, as in the screenshot below. If you see a permissions screen that means your permissions were not set correctly.
> 
> ![image](https://user-images.githubusercontent.com/65094007/175832552-3bc66abe-8579-4d02-a997-c329ff013995.png)

Hello,

I tried everything, I went through the instructions step by step. I know there is a permissions problem. I don't know how to change it.

my config:

	  
  module: "MMM-GoogleSheets",
  header: "Finnis Stundenplan",
  position: "bottom_right",
  config: {
    url: "https://script.google.com/macros/s/AKfycbzRHXjczblbZdLL72twrTkmbMAzQcK5JONVPPfOWEMRG89o-kDR/exec",
    sheet: "Finns Stundenplan",
    range: "A1:H12",
   cellStyle: "invert",
			stylesFromSheet: ["text-align", "color"],
			customStyles: ["font-size: 20px", "padding: 3px"],
			headerStyles: ["font-weight: bold"],
			styleFunc: (rowNum, colNum, cellProps) => {if(rowNum%2 == 0){return "background-color:#b4b4b42e;"}}
			}
	

<img width="1047" alt="Bildschirmfoto 2022-07-02 um 15 49 39" src="https://user-images.githubusercontent.com/108211962/177004248-a365bf5d-b66a-4bab-b2af-d536b6639f74.png">

![berechtigungen](https://user-images.githubusercontent.com/108211962/177004252-b7d65072-4166-48dc-89f4-3909138f6030.jpg)

![berech](https://user-images.githubusercontent.com/108211962/177004709-2a783272-cc08-4146-a580-b8ab5bb701fc.jpg)

**Comment by shiring11** [comment] 2022-07-07 10:31
> @shiring11 thank you for sharing that data. I might have potentially found the problem.
> 
> What is the actual sheet name for that spreadsheet? The name at the top is "Finns Studenplan" that is not the sheet name, that is the document name. What should go in the "sheet" portion of your configuration file is the sheet name (located at the bottom of your spreadsheet, not the top).

That was the solution!!

i didn't see the table name (below), renamed it now - it works!

Many thanks for your help!
<img width="871" alt="Bildschirmfoto 2022-07-07 um 12 26 43" src="https://user-images.githubusercontent.com/108211962/177753323-f88b06fc-058f-48c2-b3d3-a08fa7387dc1.png">

**Comment by ryan-d-williams** [comment] 2022-07-07 22:00
@XAGSolutions @redshiftgraphics @SARCux @YeetGott 
Recommend looking at the fix above in case it also helps you. As a summary 2 things you need to check:
1. You are actually using the sheet name, not the doc name
2. You have set the permissions to anyone, even anonymous 

I'll leave this issue open for a few weeks if anyone else wants to comment before closing!

**Comment by SARCux** [comment] 2022-09-04 14:03
Hi, @ryan-d-williams 
here my config

`//** Stundenplan
		{ 
		module: "MMM-GoogleSheets", 
		header: "Stundenplan Schule", 
		position: "top_center", 
		config: { 
			url: "https://script.google.com/macros/s/AKfycbxI3aP6W4Z8d_Dt3QYvAgj7RvZUPqQyCeX7MtNnD0cq4vFIhf1d4dJTbFhkH4LJNrx8Zg/exec", 
			sheet: "Stundenplan", 
			range: "A1:F7",
			cellStyle: "invert",
			stylesFromSheet: ["text-align", "color"],
			customStyles: ["font-size: 12px", "padding: 3px"],
			headerStyles: ["font-weight: bold"],
			styleFunc: (rowNum, colNum, cellProps) => {if(rowNum%2 == 0){return "background-color:#b4b4b42e;"}}
			}
		},	`

**Comment by 1Cedric1** [comment] 2022-09-06 06:36
Hello @ryan-d-williams 
and thank you for the opportunity to use your module.

I encounter the same situation as desribed below (TypeError: Cannot read property '0' of undefined (Zeile 11, Datei "Code"))

As I could see the permission, the option "anyone, even anonymous" is not available, when I want to deploy.

![Capture](https://user-images.githubusercontent.com/61581150/188563525-b27c4c7c-29b0-43f6-9e78-d51cc18afe0b.JPG)

Could that be the cause of this error?

Thank you for your advice !

**Comment by ryan-d-williams** [comment] 2022-09-07 03:35
> Hi, @ryan-d-williams here my config
> 
> { module: "MMM-GoogleSheets", header: "Stundenplan Schule", position: "top_center", config: { url: "https://script.google.com/macros/s/AKfycbxI3aP6W4Z8d_Dt3QYvAgj7RvZUPqQyCeX7MtNnD0cq4vFIhf1d4dJTbFhkH4LJNrx8Zg/exec", sheet: "Stundenplan", range: "A1:F7", cellStyle: "invert", stylesFromSheet: ["text-align", "color"], customStyles: ["font-size: 12px", "padding: 3px"], headerStyles: ["font-weight: bold"], styleFunc: (rowNum, colNum, cellProps) => {if(rowNum%2 == 0){return "background-color:#b4b4b42e;"}} } },

@SARCux your setup looks okay. What problem are you encountering?

**Comment by ryan-d-williams** [comment] 2022-09-07 03:37
> 

@1Cedric1 I had to type most of that into google translate so I may be incorrect, but the "everyone" option should be what you're looking for. Can you post your configuration? Make sure you are using the sheet name NOT the document name.

**Comment by 1Cedric1** [comment] 2022-09-09 08:32
Hello @ryan-d-williams 
thank you for your response and sorry for the translation effort.

Please find here some printscreens:

**the error**
![5](https://user-images.githubusercontent.com/61581150/189307021-704b1e8a-9928-4116-a7a6-02cb42a8092f.JPG)

**script in Google Sheets**
![1](https://user-images.githubusercontent.com/61581150/189307172-e87ab616-5928-4f54-b53c-fb9743164482.jpeg)

**congif in the mirror**
![3](https://user-images.githubusercontent.com/61581150/189307205-d9902082-2fd8-4728-9031-49a4dbc929f9.jpeg)

**Workbook and worksheet names**
![4](https://user-images.githubusercontent.com/61581150/189307394-57cf2dc3-9b6b-4d85-bebf-d336a510f8a3.jpeg)

On the Magic mirror, "loading..." is constant showing.

Thank you in advance for your advice

**Comment by 1Cedric1** [comment] 2022-09-13 14:04
Dear @ryan-d-williams, 

in the comment you posted on 26/06, we can see that the construct of the URL (yellow part) ...

![image](https://user-images.githubusercontent.com/61581150/189921215-dc67011f-f7c5-463d-ab66-a7df0b4a4934.png)




... is different than the URL provided by Google document ending with  "/exec".
![image](https://user-images.githubusercontent.com/61581150/189921991-ad8a9bbb-b134-4871-817c-d3b05a38e74f.png)

Could that be the cause of the "loading" problem?

**Comment by 1Cedric1** [comment] 2022-09-15 14:01
Hello @ryan-d-williams,
I could test it again in a browser, and get the codes, even if not connected with my google account:
![1](https://user-images.githubusercontent.com/61581150/190422601-ce0dc6b5-d864-47cc-a12a-55f6edbb55f0.jpeg)
as in Google Sheet. So it should not be a permission problem I suppose.
![2](https://user-images.githubusercontent.com/61581150/190422697-fc11e2de-7970-4a3f-8d68-d88605340118.jpeg)
but on the mirror, it still gets stucked
![3](https://user-images.githubusercontent.com/61581150/190422770-57ffa017-162a-4c88-9122-4939b961675b.jpeg)
Do you have an idea?

Here the picture of the google Sheet and MMM-config
![55](https://user-images.githubusercontent.com/61581150/190423891-f36654b0-021a-43f7-a0b7-28bc073996d0.jpeg)
![56](https://user-images.githubusercontent.com/61581150/190423915-24862f9f-49ab-470a-8016-fc1e0c8bbf58.jpeg)

**Comment by ambernagel** [comment] 2023-09-07 19:52
I'm having the same issue. I've followed all of the directions on the new branch. My Sheet is still called Sheet1. Here's my code: 

`			module: "MMM-GoogleSheets",
			header: "Notes",
			position: "top_right",
			classes: "default everyone",
			config: {
				url: "https://script.google.com/macros/s/AKfycbytnaUsKNDr_8Rpec97vIz0x7Bt-Vy_CCHJKH8X6cmziVQQCpuQrPyFZR2e3MHzPmcNmA/exec",
				sheet: "Sheet1",
				range: "A1:C3",
			}`

**Comment by ryan-d-williams** [comment] 2023-10-05 03:44
> Stundenplan

@1Cedric1 your configuration is still incorrect. Your sheet should be "Stundenplan" not "FE1". When I change the sheet name it works as expected. It is hanging because you have entered a sheet in the config that does not exist.

**Comment by ryan-d-williams** [comment] 2023-10-05 03:46
@ambernagel your project was not deployed correctly. When I try to access the link, I see a permissions error message. If it is deployed to anyone (even anonymous) then this message will not appear when the link is accessed.
![image](https://github.com/ryan-d-williams/MMM-GoogleSheets/assets/65094007/72adfa99-9e61-4da6-9ca2-6b9cbce98173)

**Comment by ryan-d-williams** [comment] 2024-08-09 04:08
This issue is stale so I'm closing it. Feel free to reopen if there are still issues. Note that:
1. The README has been updated for the new version of google apps script (with pictures)
2. The module now shows an error message if a sheet name is entered that does not exist

**Closed by ryan-d-williams** 2024-08-09 04:08 UTC
