### ISSUE TITLE
Love the module - couple of issues

### ISSUE THREAD

**Issue by wkswenson** [ryan-d-williams/MMM-GoogleSheets#18] opened 2021-07-29 00:17 UTC
Love this module - created a meal plan display and Stock tracker already. 

Right Align text doesn't seem to be working (always left aligns or center)
![mmm](https://user-images.githubusercontent.com/86683847/127412392-f17ae32d-bfa6-487e-b1d3-a903ef1f7e18.png)

Multi-line text doesn't seem to be working (just creates one lone run-on cell of text)

**Comment by wkswenson** [comment] 2021-07-29 00:46
Used cellStyle="flat" and that seems to fix the multi-line issue

**Comment by ryan-d-williams** [comment] 2024-08-09 03:28
@wkswenson I'm unable to reproduce this. When I text align right the text behaves as expected. Are you using the `stylesFromSheet` config option with `text-align`?

I'm also unable to reproduce the multi-line text issue. Mine is working as expected with multiline text. Feel free to post your config with a screenshot and I can take a closer look.

Glad you are enjoying the module! Please send some images of the module in use (close up) and I can add them to the README

I'm going to close this for now. Feel free to open it back up if you are still having issues.

**Closed by ryan-d-williams** 2024-08-09 03:28 UTC
